# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:31
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_pembelian_obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_beli', models.IntegerField()),
                ('total_harga_perobat_currency', djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default='IDR', editable=False, max_length=3)),
                ('total_harga_perobat', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10)),
                ('kd_obat_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obat.obat')),
            ],
        ),
        migrations.CreateModel(
            name='pembelian_obat',
            fields=[
                ('kd_pembelian', models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tgl_pembelian', models.DateField(auto_now_add=True)),
                ('total_pembelian_currency', djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default='IDR', editable=False, max_length=3)),
                ('total_pembelian', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='suplier',
            fields=[
                ('kd_suplier', models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nama_suplier', models.CharField(max_length=15)),
                ('alamat_suplier', models.TextField(validators=[django.core.validators.MaxLengthValidator(100)])),
            ],
        ),
        migrations.AddField(
            model_name='pembelian_obat',
            name='kd_suplier_obat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suplier.suplier'),
        ),
        migrations.AddField(
            model_name='detail_pembelian_obat',
            name='kd_pembelian_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suplier.pembelian_obat'),
        ),
    ]
