# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suplier',
            fields=[
                ('kd_suplier', models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nama_suplier', models.CharField(max_length=15)),
                ('alamat_suplier', models.TextField()),
            ],
        ),
    ]
