# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='kd_suplier',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
