# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pembelian_obat',
            fields=[
                ('kd_pembelian', models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tgl_pembelian', models.DateField()),
                ('total_pembelian', models.IntegerField()),
                ('kd_suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suplier.suplier')),
            ],
        ),
    ]
