# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 07:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplier', '0002_pembelian_obat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='kd_suplier',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
