# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suplier', '0004_auto_20170214_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembelian_obat',
            old_name='kd_suplier',
            new_name='kd_suplier_obat',
        ),
    ]
