# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obat', '0001_initial'),
        ('suplier', '0005_auto_20170214_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_pembelian_obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_beli', models.IntegerField()),
                ('total_harga_perobat', models.IntegerField()),
                ('kd_obat_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obat.obat')),
                ('kd_pembelian_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suplier.pembelian_obat')),
            ],
        ),
    ]
