# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suplier', '0001_initial'),
        ('obat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_pembelian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_beli', models.IntegerField()),
                ('total_harga_perobat', models.IntegerField()),
                ('kd_obat_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obat.obat')),
            ],
        ),
        migrations.CreateModel(
            name='pembelian_obat',
            fields=[
                ('kd_pembelian', models.IntegerField(primary_key=True, serialize=False)),
                ('tgl_pembelian', models.DateField()),
                ('total_pembelian', models.IntegerField()),
                ('kd_suplier_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suplier.suplier')),
            ],
        ),
        migrations.AddField(
            model_name='detail_pembelian',
            name='kd_pembelian_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.pembelian_obat'),
        ),
    ]
