# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0002_auto_20170211_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian_obat',
            name='kd_suplier_obat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suplier.suplier'),
        ),
    ]
