# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='costumer',
            fields=[
                ('kd_costumer', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nama_costumer', models.CharField(max_length=15)),
                ('alamat_costumer', models.TextField(validators=[django.core.validators.MaxLengthValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='detail_penjualan_obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_jual', models.IntegerField()),
                ('total_harga_perobat', models.IntegerField()),
                ('kd_obat_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obat.obat')),
            ],
        ),
        migrations.CreateModel(
            name='penjualan_obat',
            fields=[
                ('kd_penjualan', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tgl_penjualan', models.DateField(auto_now_add=True)),
                ('total_penjualan', models.IntegerField()),
                ('kd_costumer_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumer.costumer')),
            ],
        ),
        migrations.AddField(
            model_name='detail_penjualan_obat',
            name='kd_penjualan_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumer.penjualan_obat'),
        ),
    ]
