# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:38
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_penjualan_obat',
            name='total_harga_perobat_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default=b'IDR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='penjualan_obat',
            name='total_penjualan_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default=b'IDR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='detail_penjualan_obat',
            name='total_harga_perobat',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='penjualan_obat',
            name='total_penjualan',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10),
        ),
    ]
