# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('kode_pelanggan', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nama_pelanggan', models.CharField(max_length=50)),
                ('alamat_pelanggan', models.TextField(validators=[django.core.validators.MaxLengthValidator(100)])),
                ('nomer_telepon', models.CharField(max_length=20)),
            ],
        ),
    ]
