# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pemesanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('kode_penjualan', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tanggal_penjualan', models.DateField(auto_now_add=True)),
                ('kode_pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pemesanan.Pemesanan')),
            ],
        ),
    ]
