# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumer', '0001_initial'),
        ('obat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_penjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_jual', models.IntegerField()),
                ('total_harga_perobat', models.IntegerField()),
                ('kd_obat_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obat.obat')),
            ],
        ),
        migrations.CreateModel(
            name='penjualan_obat',
            fields=[
                ('kd_penjualan', models.IntegerField(primary_key=True, serialize=False)),
                ('tgl_penjualan', models.DateField()),
                ('total_penjualan', models.IntegerField()),
                ('kd_costumer_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumer.costumer')),
            ],
        ),
        migrations.AddField(
            model_name='detail_penjualan',
            name='kd_penjualan_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjualan.penjualan_obat'),
        ),
    ]
