# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:59
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Obat', '0001_initial'),
        ('Pemesanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPenjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('total_harga_perobat_currency', djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default='IDR', editable=False, max_length=3)),
                ('total_harga_perobat', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10)),
                ('kd_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obat.Obat')),
            ],
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('kode_penjualan', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tanggal_penjualan', models.DateField(auto_now_add=True)),
                ('total_penjualan_currency', djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default='IDR', editable=False, max_length=3)),
                ('total_penjualan', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10)),
                ('kode_pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pemesanan.Pemesanan')),
            ],
        ),
        migrations.AddField(
            model_name='detailpenjualan',
            name='kode_penjualan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penjualan.Penjualan'),
        ),
    ]
