# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiodataKaryawan',
            fields=[
                ('kode_karyawan', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('nama_karyawan', models.CharField(max_length=50)),
                ('tanggal_lahir_karyawan', models.DateField()),
                ('alamat_karyawan', models.TextField(validators=[django.core.validators.MaxLengthValidator(100)])),
                ('telepon_karyawan', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('email_karyawan', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='akun_karyawan',
            name='kode_karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.BiodataKaryawan'),
        ),
    ]
