# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absen_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_karyawan', models.CharField(max_length=50)),
                ('jenis_kehadiran', models.CharField(choices=[('izin', 'Izin'), ('hadir', 'Hadir'), ('alpa', 'Tanpa Kehadiran'), ('cuti', 'Cuti')], default='hadir', max_length=50)),
                ('waktu', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Akun_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Biodata_Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_karyawan', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField(validators=[django.core.validators.MaxLengthValidator(100)])),
                ('telepon', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('email_karyawan', models.EmailField(blank=True, max_length=254)),
                ('shift_kerja', models.CharField(choices=[('malam', 'Malam'), ('pagi/siang', 'Pagi/Siang')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Izin_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kehadiran', models.CharField(choices=[('izin', 'Izin'), ('cuti', 'Cuti')], max_length=50)),
                ('waktu_mulai', models.DateField(auto_now_add=True)),
                ('waktu_berhenti', models.DateField()),
                ('alasan', models.TextField(validators=[django.core.validators.MaxLengthValidator(150)])),
                ('disetujui', models.BooleanField(default=False)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.Biodata_Karyawan')),
            ],
        ),
        migrations.AddField(
            model_name='akun_karyawan',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.Biodata_Karyawan'),
        ),
        migrations.AddField(
            model_name='absen_karyawan',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.Biodata_Karyawan'),
        ),
    ]
