# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Karyawan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akun_karyawan',
            old_name='karyawan',
            new_name='kode_karyawan',
        ),
    ]
