# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absen_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kehadiran', models.CharField(choices=[('cuti', 'Cuti'), ('hadir', 'Hadir'), ('izin', 'Izin'), ('alpa', 'Tanpa Kehadiran')], max_length=50)),
                ('waktu', models.DateField(auto_now_add=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.BiodataKaryawan')),
                ('shift_kerja_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.Akun_karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Izin_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kehadiran', models.CharField(choices=[('izin', 'Izin'), ('cuti', 'Cuti')], max_length=50)),
                ('waktu_mulai', models.DateField()),
                ('waktu_berhenti', models.DateField()),
                ('alasan', models.TextField(validators=[django.core.validators.MaxLengthValidator(150)])),
                ('disetujui', models.BooleanField(default=False)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.BiodataKaryawan')),
            ],
        ),
    ]
