# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Karyawan', '0002_remove_absen_karyawan_nama_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen_karyawan',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.Akun_karyawan'),
        ),
    ]
