# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pelanggan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Resep',
            fields=[
                ('kode_resep', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tanggal_resep', models.DateField()),
                ('nama_pasien', models.CharField(max_length=50)),
                ('kode_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pelanggan.Data_Pelanggan')),
            ],
        ),
    ]
