# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:31
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obat',
            fields=[
                ('kd_obat', models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nama_obat', models.CharField(max_length=15)),
                ('tipe_obat', models.CharField(choices=[('obat bebas terbatas', 'Obat Bebas Terbatas'), ('obat keras dan psikotropika', 'Obat Keras dan Psikotropika'), ('obat bebas', 'Obat Bebas')], max_length=35)),
                ('harga_jual_currency', djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default='IDR', editable=False, max_length=3)),
                ('harga_jual', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10)),
            ],
        ),
    ]
