# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 03:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obat',
            fields=[
                ('kd_obat', models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nama_obat', models.CharField(max_length=15)),
                ('tipe_obat', models.CharField(max_length=15)),
                ('harga_jual', models.IntegerField()),
            ],
        ),
    ]
