# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:21
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Suplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Obat',
            fields=[
                ('kode_obat', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nama_obat', models.CharField(max_length=100)),
                ('jenis_obat', models.CharField(choices=[('obat bebas terbatas', 'Obat Bebas Terbatas'), ('obat keras', 'Obat Keras'), ('obat bebas', 'Obat Bebas')], max_length=20)),
                ('bentuk_obat', models.CharField(choices=[('pil', 'PIL'), ('tablet', 'Tablet'), ('salep', 'Salep'), ('larutan', 'Larutan'), ('suspensi', 'Suspensi'), ('serbuk', 'Serbuk'), ('kapsul', 'Kapsul')], max_length=20)),
                ('harga_obat_currency', djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default='IDR', editable=False, max_length=3)),
                ('harga_obat', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10)),
                ('stock_obat', models.IntegerField()),
                ('nama_suplier', models.CharField(max_length=50)),
                ('kode_suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suplier.Data_Suplier')),
            ],
        ),
    ]
