# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resep', '0001_initial'),
        ('Karyawan', '0001_initial'),
        ('Pelanggan', '0001_initial'),
        ('Obat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('kode_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obat.Obat')),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('kode_pemesanan', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tanggal_pemesanan', models.DateField(auto_now_add=True)),
                ('kode_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.BiodataKaryawan')),
                ('kode_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pelanggan.Pelanggan')),
            ],
        ),
        migrations.AddField(
            model_name='detailpemesanan',
            name='kode_pemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pemesanan.Pemesanan'),
        ),
        migrations.AddField(
            model_name='detailpemesanan',
            name='kode_resep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resep.Resep'),
        ),
    ]
