# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pelanggan', '0001_initial'),
        ('Karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('kode_pemesanan', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tanggal_pemesanan', models.DateField(auto_now_add=True)),
                ('kode_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.BiodataKaryawan')),
                ('kode_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pelanggan.Pelanggan')),
            ],
        ),
    ]
