# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:21
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resep', '0001_initial'),
        ('Pelanggan', '0001_initial'),
        ('Karyawan', '0001_initial'),
        ('Obat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Pemesanan',
            fields=[
                ('kode_pemesanan', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tanggal_pemesanan', models.DateField(auto_now_add=True)),
                ('nama_pelanggan', models.CharField(max_length=50)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Karyawan.Biodata_Karyawan')),
                ('kode_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pelanggan.Data_Pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemesan', models.CharField(max_length=50)),
                ('nama_obat', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField()),
                ('total_harga_perobat_currency', djmoney.models.fields.CurrencyField(choices=[(b'IDR', b'Rupiah'), (b'USD', 'US Dollar')], default='IDR', editable=False, max_length=3)),
                ('total_harga_perobat', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'IDR', max_digits=10)),
                ('kode_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obat.Data_Obat')),
                ('kode_pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pemesanan.Data_Pemesanan')),
                ('kode_resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resep.Data_Resep')),
            ],
        ),
    ]
