# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resep', '0001_initial'),
        ('Obat', '0001_initial'),
        ('Pemesanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('kode_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obat.Obat')),
                ('kode_pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pemesanan.Pemesanan')),
                ('kode_resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resep.Resep')),
            ],
        ),
    ]
