# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pemesanan', '0002_auto_20170303_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpemesanan',
            name='kode_resep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resep.Data_Resep'),
        ),
    ]
